name: test-firestormviewer
version: '1.1'
summary: A SecondLife Viewer
description: |
  An app to login and view virtual worlds like
  SecondLife and OpenSimulator
architectures:
  - amd64

grade: devel
confinement: devmode
base: core18

apps:
  test-firestormviewer:
    command: desktop-launch $SNAP/run-firestorm
    plugs:
      - x11
      - network
      - opengl
      - pulseaudio
      - wayland
      - desktop
      - desktop-legacy
      - browser-support
      - home

parts:
  launcher:
    plugin: dump
    source: scripts
  
  enable-i386:
    plugin: nil
    override-build: |
      dpkg --add-architecture i386
      apt update

  viewer:
    after: [enable-i386]
    plugin: nil
    stage-packages:
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libidn11:i386
      - libstdc++6:i386
      - libuuid1:i386
      - zlib1g:i386
      - gstreamer0.10-pulseaudio:i386
      - pepperflashplugin-nonfree
      - libnss3:i386
      - libnspr4:i386
      - libxtst6:i386
      - libgconf-2-4:i386
      - libxss1:i386
      - x11-xserver-utils
      - libxss1
      - libcurl3
      - python3-gi
      - python3-gi-cairo
      - python3-cairo
      - xz-utils
