name: test-firestormviewer
version: '1.1.1'
summary: A SecondLife Viewer
description: |
  An app to login and view virtual worlds like
  SecondLife and OpenSimulator
architectures:
  - amd64

grade: devel
confinement: devmode
base: core18

apps:
  test-firestormviewer:
    command: run-firestorm
    plugs:
      - x11
      - alsa
      - network
      - opengl
      - pulseaudio
      - wayland
      - desktop
      - desktop-legacy
      - browser-support
      - home

parts:
  launcher:
    plugin: dump
    source: scripts
  
  enable-i386:
    plugin: nil
    override-build: |
      dpkg --add-architecture i386
      apt update

  viewer:
    after: [enable-i386]
    plugin: nil
    stage-packages:
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libglu1-mesa
      - libopenal1
      - libopenal1:i386
      - libopenal-dev
      - libgstreamer-plugins-base1.0-0
      - libalut0
      - libpulse0
      - libgstreamer1.0-0
      - libalut-dev
      - libidn11:i386
      - libstdc++6:i386
      - libuuid1:i386
      - zlib1g:i386
      - gstreamer1.0-pulseaudio:i386
      - gstreamer1.0-pulseaudio
      - gstreamer1.0-plugins-base:i386
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good:i386
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-ugly:i386
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-plugins-bad:i386
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-alsa:i386
      - gstreamer1.0-alsa
      - pepperflashplugin-nonfree
      - libnss3:i386
      - libnspr4:i386
      - libxtst6:i386
      - libgconf-2-4:i386
      - libxss1:i386
      - x11-xserver-utils
      - libxss1
      - libcurl3
      - python3-gi
      - python3-gi-cairo
      - python3-cairo
      - xz-utils
